// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restrauntBooking;

#nullable disable

namespace turfbooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241219101321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("restrauntBooking.Slot", b =>
                {
                    b.Property<int>("slotid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slotid"));

                    b.Property<string>("slotdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slottime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("slotid");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("restrauntBooking.SlotBooking", b =>
                {
                    b.Property<int>("bookingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingid"));

                    b.Property<string>("custname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("slotid")
                        .HasColumnType("int");

                    b.HasKey("bookingid");

                    b.ToTable("SlotBookings");
                });

            modelBuilder.Entity("restrauntBooking.TurfUser", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usertype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.ToTable("TurfUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
